version: 0.2

env:
  parameter-store:
    SSM_AccountServer_DETAILS: "AccountServer_DETAILS"
    SSM_GameDB_DETAILS: "GameDB_DETAILS"
phases:
  install:
    runtime-versions:
      nodejs: 12

  pre_build:
    commands:
      - bash build/install.sh
  
  build:
    commands:
      - bash build/build.sh
  
  post_build:
    commands:
      - echo Moving build output
      - mkdir build-output
      - cp -R api/dist/* build-output
      - mkdir build-output/node_modules
      - cp -R api/node_modules build-output/
      - cp api/package.json build-output/
      - cp api/.env build-output/.env
      - cp buildspec.yaml build-output/buildspec.yaml
      - cp appspec.yml build-output/appspec.yml
      - mkdir build-output/build
      - cp -R build/ build-output/
artifacts:
  files:
    - '**/*'
  base-directory: build-output
  name: topcms
