const ActionTypes = {
  bootstrapApplication: 'bootstrapApplication',
  retrieveLandingPageInformation: 'retrieveLandingPageInformation',
  registerUser: 'registerUser',
  setInitialRoute: 'setInitialRoute',
  changeRoute: 'changeRoute',
  loginUser: 'loginUser',
  retrieveUser: 'retrieveUser',
  getServerStats: 'getServerStats',
  getSiteAuthors: 'getSiteAuthors',
  getSiteNewsArticles: 'getSiteNewsArticles',
  getSiteDownloads: 'getSiteDownloads',
  getSitePolls: 'getSitePolls',
  getAllSiteInfo: 'getAllSiteInfo',
  createSiteAuthor: 'createSiteAuthor',
  updateSiteAuthor: 'updateSiteAuthor',
  deleteSiteAuthor: 'deleteSiteAuthor',
  createSiteDownload: 'createSiteDownload',
  updateSiteDownload: 'updateSiteDownload',
  deleteSiteDownload: 'deleteSiteDownload',
  createSiteNews: 'createSiteNews',
  updateSiteNews: 'updateSiteNews',
  deleteSiteNews: 'deleteSiteNews',
  getSiteDownload: 'getSiteDownload',
  getSiteNewsArticle: 'getSiteNewsArticle',
  getSiteAuthor: 'getSiteAuthor',
};

export default ActionTypes;
