const MutationTypes = {
  APPLICATION_LOADING: 'APPLICATION_LOADING',
  APPLICATION_LOADED: 'APPLICATION_LOADED',
  REGISTERING_USER: 'REGISTERING_USER',
  REGISTRATION_COMPLETE: 'REGISTRATION_COMPLETE',
  SIGNING_IN_USER: 'SIGNING_IN_USER',
  SIGNIN_COMPLETE: 'SIGNIN_COMPLETE',
  CHANGE_ROUTE: 'CHANGE_ROUTE',
};

export default MutationTypes;
