export const LOGIN_IN_PROGRESS = 'LOGIN_IN_PROGRESS';
export const LOGIN_COMPLETED = 'LOGIN_COMPLETED';
export const SIGNUP_IN_PROGRESS = 'SIGNUP_IN_PROGRESS';
export const SIGNUP_COMPLETED = 'SIGNUP_COMPLETED';
export const USER_UNAUTHORIZED = 'USER_UNAUTHORIZED';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const CHANGING_ROUTE = 'CHANGING_ROUTE';